version: "3.7"

services:
  app:
    container_name: shopping_cart
    build:
      context: .
    ports:
      - '3001:3000'
    volumes:
      - .:/var/www/app
    labels:
      com.datadoghq.ad.logs: '[{"source": "ruby", "service": "app"}]'
    environment:
      DATADOG_HOST: datadog
  datadog:
    image: datadog/agent:latest
    links:
      - app
    environment:
      - DD_API_KEY=cf1f6ba15b7cd81ad80e4fddef053ad8
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
      - DD_AC_INCLUDE="name:shopping_cart"
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_SITE=datadoghq.eu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
